version: '3'

services:
  nodejs:
    container_name: nodejs
    image: node:10-alpine
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=delvelop
    command:
      "npm start"
    volumes:
      - ./nodejs:/app
    links:
      - mariaDB
      - mongoDB
      - mssqlDB

  mariaDB:
    container_name: mariaDB
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes: 
    - /data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariaDB
      - PMA_PORT=3306
    links:
      - mariaDB

  mongoDB:
    container_name: mongoDB
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./db:/etc/mongo

  mssqlDB:
    container_name: mssqlDB
    image: microsoft/mssql-server-linux
    ports:
      - 1433:1433
    volumes:
      - ./temp:/temp
    environment:
      - ACCEPT_EULA=Y
      - sa_password=123456
      - attach_dbs=[{'dbName':'SampleDB','dbFiles':['C:\\temp\\sampledb.mdf','C:\\temp\\sampledb_log.ldf']}]